# Generated by Django 3.0.8 on 2020-08-04 07:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, validators=[django.core.validators.MaxLengthValidator(50, '50文字まででお願いします。')], verbose_name='Name')),
                ('sort', models.CharField(choices=[('red', 'red'), ('white', 'white'), ('sparkling', 'sparkling')], max_length=100, verbose_name='Sort')),
                ('country', models.CharField(choices=[('France', 'France'), ('Italy', 'Italy'), ('Germany', 'Germany'), ('Spain', 'Spain'), ('Portugal', 'Portugal'), ('USA', 'USA'), ('Australia', 'Australia'), ('New Zealand', 'New Zealand'), ('Argentina', 'Argentina'), ('Chile', 'Chile'), ('South Africa', 'South Africa'), ('Japan', 'Japan'), ('etc.', 'etc.')], max_length=100, verbose_name='Country')),
                ('vintage', models.CharField(blank=True, choices=[('1980', '1980'), ('1981', '1981'), ('1982', '1982'), ('1983', '1983'), ('1984', '1984'), ('1985', '1985'), ('1986', '1986'), ('1987', '1987'), ('1988', '1988'), ('1989', '1989'), ('1990', '1990'), ('1991', '1991'), ('1992', '1992'), ('1993', '1993'), ('1994', '1994'), ('1995', '1995'), ('1996', '1996'), ('1997', '1997'), ('1998', '1998'), ('1999', '1999'), ('2000', '2000'), ('2001', '2001'), ('2002', '2002'), ('2003', '2003'), ('2004', '2004'), ('2005', '2005'), ('2006', '2006'), ('2007', '2007'), ('2008', '2008'), ('2009', '2009'), ('2010', '2010'), ('2011', '2011'), ('2012', '2012'), ('2013', '2013'), ('2014', '2014'), ('2015', '2015'), ('2016', '2016'), ('2017', '2017'), ('2018', '2018'), ('2019', '2019'), ('2020', '2020')], max_length=100, verbose_name='Vintage')),
                ('grape', models.CharField(blank=True, choices=[('Chardonnay', 'Chardonnay'), ('Sauvignon Blanc', 'Sauvignon Blanc'), ('Riesling', 'Riesling'), ('Gewürztraminer', 'Gewürztraminer'), ('Semillon', 'Semillon'), ('Viognier', 'Viognier'), ('Pino Blanc', 'Pino Blanc'), ('Muscadet', 'Muscadet'), ('Pino gris', 'Pino gris'), ('Cortese', 'Cortese'), ('Trebbiano', 'Trebbiano'), ('Garganega', 'Garganega'), ('Malvasia', 'Malvasia'), ('Chenin Blanc', 'Chenin Blanc'), ('Albariño', 'Albariño'), ('甲州', '甲州'), ('etc.', 'etc.')], max_length=100, verbose_name='Grape')),
                ('eye', models.CharField(blank=True, choices=[('green', 'green'), ('lemon yellow', 'lemon yellow'), ('yellow', 'yellow'), ('gold', 'gold'), ('amber', 'amber')], max_length=100, verbose_name='Eye')),
                ('nose', models.CharField(blank=True, choices=[('lemmon', 'レモン'), ('kime', 'ライム'), ('grapefruit', 'グレープフルーツ'), ('apple', 'リンゴ'), ('green apple', '青りんご'), ('pear', '洋ナシ'), ('peach', '桃'), ('apricot', 'アプリコット'), ('pineapple', 'パイナップル'), ('passion fruit', 'パッションフルーツ'), ('banana', 'バナナ'), ('mango', 'マンゴー'), ('lychee', 'ライチ'), ('muscat', 'マスカット'), ('water melon', 'メロン'), ('kinmokusei', 'キンモクセイ'), ('mint', 'ミント'), ('rose', 'バラ'), ('floral', 'お花のような'), ('herb', 'ハーブの'), ('perfume', '香水'), ('barrel incense', '樽香'), ('toast', 'トースト'), ('butter', 'バター'), ('vanila', 'バニラ'), ('sulfur', '硫黄'), ('honey', 'はちみつ'), ('cinnamon', 'シナモン'), ('mineral', 'ミネラル')], max_length=100, verbose_name='Nose')),
                ('mouth', models.CharField(blank=True, choices=[('fresh', 'フレッシュ感のある'), ('dry', 'ドライな'), ('sour', '酸味が目立つ'), ('balance', 'バランスの良い'), ('sweat', '甘さのある'), ('fruity', 'フルーツ感のある'), ('elegant', 'エレガントな,綺麗な'), ('mineral', 'ミネラルのある'), ('rich', '芳醇な、豊かな'), ('thick', '厚みのある'), ('strong', '濃縮し力強い'), ('aging', '長期熟成型のような')], max_length=100, verbose_name='Mouth')),
                ('date', models.DateField(verbose_name='Date')),
                ('memo', models.CharField(blank=True, max_length=200, verbose_name='Memo')),
                ('point', models.FloatField(validators=[django.core.validators.MaxValueValidator(5, '点数は5点までで採点お願い致します。'), django.core.validators.MinValueValidator(0, '点数は0点以上で採点お願い致します。')], verbose_name='Point')),
                ('pic', models.ImageField(blank=True, upload_to='images/', validators=[django.core.validators.FileExtensionValidator(['JPG', 'PNG', 'GIF'], 'ファイル形式はJPEG,PNG,GIFでお願い致します。')])),
            ],
        ),
    ]
