# Generated by Django 3.0.8 on 2020-08-04 15:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wine',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='wine',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
